package edu.northeastern.group15_assignment;

import java.util.List;

public interface ColorMindBackendConnector {

    /**
     * Initiate generation of palette of colors that align with the color provided
     * @param color Hex string of color
     */
    public void initiatePaletteGeneration(String color);

    /**
     * Check if the process is still on going.
     * @return
     */
    public boolean isInProgess();

    /**
     * Retrieves the list of colors generated by the API
     * @return
     */
    public List<String> retrievePalette();
}
